### ISSUE TITLE
Service Endpoint routing broken by fix for route reflector Cluster IP advertisement

### ISSUE THREAD

**Issue by mleklund** [projectcalico/confd#253] opened 2019-07-10 21:25 UTC
Issue #199 's fix for Cluster IP advertisement via route reflectors in MR #206 broke the non-route reflector endpoint advertisement feature  talked about is this article: https://www.projectcalico.org/kubernetes-service-ip-route-advertisement/

I have only tested a setup with node to node mesh talking to an external bird daemon as explained in the article.

My BGPConfiguration:

```
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info
  asNumber: 64512
```
 
my BGPPeer:

```
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: bgppeer-global-5141
spec:
  peerIP: 10.10.51.41
  asNumber: 64513
```

My external-node bird.cfg:

```
# Configure logging
log syslog { debug, trace, info, remote, warning, error, auth, fatal, bug };
log stderr all;

# Override router ID
router id 10.10.51.41;


filter import_kernel {
if ( net != 0.0.0.0/0 ) then {
   accept;
   }
reject;
}

# Turn on global debugging of all protocols
debug protocols all;

# This pseudo-protocol watches all interface up/down events.
protocol device {
  scan time 2;    # Scan interfaces every 2 seconds
}

protocol kernel {
  metric 0;
  learn;
  import none;
  export all;
  merge paths yes;
}

protocol bgp k8test2 {
  description "10.10.51.41";
  local as 64513;
  neighbor 10.10.51.40 as 64512;
  graceful restart;
  import all;
  export all;
}

protocol bgp k8test1 {
  description "10.10.51.41";
  local as 64513;
  neighbor 10.10.51.39 as 64512;
  graceful restart;
  import all;
  export all;
}

protocol bgp k8test3 {
  description "10.10.51.41";
  local as 64513;
  neighbor 10.10.51.42 as 64512;
  graceful restart;
  import all;
  export all;
}
```

On calico 3.4 with nginx deployment set to replica=1, and service deployed I get the following from `ip route`

```
10.10.50.0/23 dev eth0  proto kernel  scope link  src 10.10.51.41
10.96.0.0/12  proto bird
	nexthop via 10.10.51.39  dev eth0 weight 1
	nexthop via 10.10.51.40  dev eth0 weight 1
	nexthop via 10.10.51.42  dev eth0 weight 1
10.98.234.1 via 10.10.51.40 dev eth0  proto bird
10.120.0.0/24  proto bird
	nexthop via 10.10.51.39  dev eth0 weight 1
	nexthop via 10.10.51.40  dev eth0 weight 1
	nexthop via 10.10.51.42  dev eth0 weight 1
10.120.1.0/24  proto bird
	nexthop via 10.10.51.39  dev eth0 weight 1
	nexthop via 10.10.51.40  dev eth0 weight 1
	nexthop via 10.10.51.42  dev eth0 weight 1
10.120.2.0/24  proto bird
	nexthop via 10.10.51.39  dev eth0 weight 1
	nexthop via 10.10.51.40  dev eth0 weight 1
	nexthop via 10.10.51.42  dev eth0 weight 1
```

and the following from `bird show route`:

```
10.98.234.1/32     via 10.10.51.40 on eth0 [k8test2 16:21:49] * (100) [AS64512i]
10.96.0.0/12       via 10.10.51.39 on eth0 [k8test1 16:18:50] * (100) [AS64512i]
                   via 10.10.51.42 on eth0 [k8test3 16:18:50] (100) [AS64512i]
                   via 10.10.51.40 on eth0 [k8test2 16:18:50] (100) [AS64512i]
10.120.2.0/24      via 10.10.51.39 on eth0 [k8test1 16:18:50] * (100) [AS64512i]
                   via 10.10.51.42 on eth0 [k8test3 16:18:50] (100) [AS64512i]
                   via 10.10.51.40 on eth0 [k8test2 16:18:50] (100) [AS64512i]
10.120.0.0/24      via 10.10.51.39 on eth0 [k8test1 16:18:50] * (100) [AS64512i]
                   via 10.10.51.42 on eth0 [k8test3 16:18:50] (100) [AS64512i]
                   via 10.10.51.40 on eth0 [k8test2 16:18:50] (100) [AS64512i]
10.120.1.0/24      via 10.10.51.39 on eth0 [k8test1 16:18:50] * (100) [AS64512i]
                   via 10.10.51.42 on eth0 [k8test3 16:18:50] (100) [AS64512i]
                   via 10.10.51.40 on eth0 [k8test2 16:18:50] (100) [AS64512i]
```

And with replicas=2, I get the following from `ip route`:

```
default via 10.10.50.1 dev eth0
10.10.50.0/23 dev eth0  proto kernel  scope link  src 10.10.51.41
10.96.0.0/12  proto bird
	nexthop via 10.10.51.39  dev eth0 weight 1
	nexthop via 10.10.51.40  dev eth0 weight 1
	nexthop via 10.10.51.42  dev eth0 weight 1
10.98.234.1  proto bird
	nexthop via 10.10.51.40  dev eth0 weight 1
	nexthop via 10.10.51.42  dev eth0 weight 1
10.120.0.0/24  proto bird
	nexthop via 10.10.51.39  dev eth0 weight 1
	nexthop via 10.10.51.40  dev eth0 weight 1
	nexthop via 10.10.51.42  dev eth0 weight 1
10.120.1.0/24  proto bird
	nexthop via 10.10.51.39  dev eth0 weight 1
	nexthop via 10.10.51.40  dev eth0 weight 1
	nexthop via 10.10.51.42  dev eth0 weight 1
10.120.2.0/24  proto bird
	nexthop via 10.10.51.39  dev eth0 weight 1
	nexthop via 10.10.51.40  dev eth0 weight 1
	nexthop via 10.10.51.42  dev eth0 weight 1
```

and with replicas=2, I get the following from `birdc show route`

```
10.98.234.1/32     via 10.10.51.40 on eth0 [k8test2 16:21:49] * (100) [AS64512i]
                   via 10.10.51.42 on eth0 [k8test3 17:00:00] (100) [AS64512i]
10.96.0.0/12       via 10.10.51.39 on eth0 [k8test1 16:18:50] * (100) [AS64512i]
                   via 10.10.51.42 on eth0 [k8test3 16:18:50] (100) [AS64512i]
                   via 10.10.51.40 on eth0 [k8test2 16:18:50] (100) [AS64512i]
10.120.2.0/24      via 10.10.51.39 on eth0 [k8test1 16:18:50] * (100) [AS64512i]
                   via 10.10.51.42 on eth0 [k8test3 16:18:50] (100) [AS64512i]
                   via 10.10.51.40 on eth0 [k8test2 16:18:50] (100) [AS64512i]
10.120.0.0/24      via 10.10.51.39 on eth0 [k8test1 16:18:50] * (100) [AS64512i]
                   via 10.10.51.42 on eth0 [k8test3 16:18:50] (100) [AS64512i]
                   via 10.10.51.40 on eth0 [k8test2 16:18:50] (100) [AS64512i]
10.120.1.0/24      via 10.10.51.39 on eth0 [k8test1 16:18:50] * (100) [AS64512i]
                   via 10.10.51.42 on eth0 [k8test3 16:18:50] (100) [AS64512i]
                   via 10.10.51.40 on eth0 [k8test2 16:18:50] (100) [AS64512i]
```

With calico 3.7, that is not the case, I get something like this from `ip route`:

```
10.10.50.0/23 dev eth0  proto kernel  scope link  src 10.10.51.41
10.96.0.0/12  proto bird
	nexthop via 10.10.51.39  dev eth0 weight 1
	nexthop via 10.10.51.40  dev eth0 weight 1
	nexthop via 10.10.51.42  dev eth0 weight 1
10.98.234.1  proto bird
	nexthop via 10.10.51.39  dev eth0 weight 1
	nexthop via 10.10.51.40  dev eth0 weight 1
	nexthop via 10.10.51.42  dev eth0 weight 1
10.120.1.0/26  proto bird
	nexthop via 10.10.51.39  dev eth0 weight 1
	nexthop via 10.10.51.40  dev eth0 weight 1
	nexthop via 10.10.51.42  dev eth0 weight 1
10.120.2.0/26  proto bird
	nexthop via 10.10.51.39  dev eth0 weight 1
	nexthop via 10.10.51.40  dev eth0 weight 1
	nexthop via 10.10.51.42  dev eth0 weight 1
10.120.137.192/26  proto bird
	nexthop via 10.10.51.39  dev eth0 weight 1
	nexthop via 10.10.51.40  dev eth0 weight 1
	nexthop via 10.10.51.42  dev eth0 weight 1
```

```
10.120.137.192/26  via 10.10.51.39 on eth0 [k8test1 17:10:03] * (100) [AS64512i]
                   via 10.10.51.40 on eth0 [k8test2 17:10:03] (100) [AS64512i]
                   via 10.10.51.42 on eth0 [k8test3 17:10:03] (100) [AS64512i]
10.98.234.1/32     via 10.10.51.39 on eth0 [k8test1 17:12:47] * (100) [AS64512i]
                   via 10.10.51.40 on eth0 [k8test2 17:12:40] (100) [AS64512i]
                   via 10.10.51.42 on eth0 [k8test3 17:12:23] (100) [AS64512i]
10.96.0.0/12       via 10.10.51.39 on eth0 [k8test1 17:12:47] * (100) [AS64512i]
                   via 10.10.51.40 on eth0 [k8test2 17:12:40] (100) [AS64512i]
                   via 10.10.51.42 on eth0 [k8test3 17:12:23] (100) [AS64512i]
10.120.2.0/26      via 10.10.51.39 on eth0 [k8test1 17:10:03] * (100) [AS64512i]
                   via 10.10.51.40 on eth0 [k8test2 17:10:03] (100) [AS64512i]
                   via 10.10.51.42 on eth0 [k8test3 17:10:03] (100) [AS64512i]
10.120.1.0/26      via 10.10.51.39 on eth0 [k8test1 17:10:03] * (100) [AS64512i]
                   via 10.10.51.40 on eth0 [k8test2 17:10:03] (100) [AS64512i]
                   via 10.10.51.42 on eth0 [k8test3 17:10:03] (100) [AS64512i]
```

So while it did not work as documented for the case reported in #199, it does not work as documented for an out of the box node mesh now.  This regression was introduced in calico 3.6.

Discussion thread working out the issue on slack is here:

https://calicousers.slack.com/archives/C0BC91S9F/p1562774446157100

**Comment by caseydavenport** [comment] 2019-07-10 23:50
@mleklund thanks for the detailed investigation! I agree this looks like a bug as you've described. 

I think fundamentally we've got this situation:
- Route reflector nodes should advertise the full cluster IP route, plus any /32 routes for Local services on any node.
- Regular nodes should advertise the full cluster IP route, plus Local-type services that are actually local to that node.

The previous fix tried to solve the first case by advertising all routes within the cluster CIDR, but missed that the behavior would occur on all nodes. So, I think we can fix this by scoping the original fix so that it only occurs when the node is acting as a route reflector.

**Comment by caseydavenport** [comment] 2019-07-11 00:14
Actually, I think my assessment above is wrong. 

Our route generation code shouldn't be generating /32 routes on non-local nodes at all: https://github.com/projectcalico/confd/blob/master/pkg/backends/calico/routes.go#L220-L253

So then, where is this route coming from? It seems like each node is learning routes from other nodes via the full mesh, and then re-advertising those routes to the external node and replacing itself as the next hop.

You can actually see it's doing it with pod IP routes as well. For example, the following isn't what you want either (and can be seen in the "working" v3.4 example as well)

```
10.120.1.0/26      via 10.10.51.39 on eth0 [k8test1 17:10:03] * (100) [AS64512i]
                   via 10.10.51.40 on eth0 [k8test2 17:10:03] (100) [AS64512i]
                   via 10.10.51.42 on eth0 [k8test3 17:10:03] (100) [AS64512i]
```

I think the demo scenario here might be slightly unusual. Normally we'd expect either:
- A L3 TOR to which all nodes peer, with no full-mesh
- A L2 network with one or more route reflectors to which all nodes peer, and then peer the RRs to whichever other routers you so desire.

You might try setting the external BIRD instance to be in the same AS as Calico - this _might_ leave the original next hop intact.

I'll try to think about this more to figure out what the right behavior should be.

**Comment by mleklund** [comment] 2019-07-11 20:40
If I set `nodeToNodeMeshEnabled: false`, still not using any reflectors I think I get what you expect with 3.7, I think:

```
default via 10.10.50.1 dev eth0
10.10.50.0/23 dev eth0  proto kernel  scope link  src 10.10.51.41
10.96.0.0/12  proto bird
	nexthop via 10.10.51.39  dev eth0 weight 1
	nexthop via 10.10.51.40  dev eth0 weight 1
	nexthop via 10.10.51.42  dev eth0 weight 1
10.100.29.239  proto bird
	nexthop via 10.10.51.40  dev eth0 weight 1
	nexthop via 10.10.51.42  dev eth0 weight 1
10.120.1.0/26 via 10.10.51.42 dev eth0  proto bird
10.120.2.0/26 via 10.10.51.40 dev eth0  proto bird
10.120.137.192/26 via 10.10.51.39 dev eth0  proto bird
```

```
10.100.29.239/32   via 10.10.51.40 on eth0 [k8test2 16:18:28] * (100) [AS64512i]
                   via 10.10.51.42 on eth0 [k8test3 16:18:26] (100) [AS64512i]
10.120.137.192/26  via 10.10.51.39 on eth0 [k8test1 16:17:47] * (100) [AS64512i]
10.96.0.0/12       via 10.10.51.39 on eth0 [k8test1 16:17:47] * (100) [AS64512i]
                   via 10.10.51.40 on eth0 [k8test2 16:17:48] (100) [AS64512i]
                   via 10.10.51.42 on eth0 [k8test3 16:17:48] (100) [AS64512i]
10.120.2.0/26      via 10.10.51.40 on eth0 [k8test2 16:17:48] * (100) [AS64512i]
10.120.1.0/26      via 10.10.51.42 on eth0 [k8test3 16:17:48] * (100) [AS64512i]
```

Versus 3.4:

```
10.10.50.0/23 dev eth0  proto kernel  scope link  src 10.10.51.41
10.96.0.0/12  proto bird
	nexthop via 10.10.51.39  dev eth0 weight 1
	nexthop via 10.10.51.40  dev eth0 weight 1
	nexthop via 10.10.51.42  dev eth0 weight 1
10.111.69.177  proto bird
	nexthop via 10.10.51.40  dev eth0 weight 1
	nexthop via 10.10.51.42  dev eth0 weight 1
10.120.0.0/24 via 10.10.51.39 dev eth0  proto bird
10.120.1.0/24 via 10.10.51.42 dev eth0  proto bird
10.120.2.0/24 via 10.10.51.40 dev eth0  proto bird
```

```
10.111.69.177/32   via 10.10.51.40 on eth0 [k8test2 11:37:08] * (100) [AS64512i]
                   via 10.10.51.42 on eth0 [k8test3 11:41:29] (100) [AS64512i]
10.96.0.0/12       via 10.10.51.39 on eth0 [k8test1 11:36:22] * (100) [AS64512i]
                   via 10.10.51.40 on eth0 [k8test2 11:36:21] (100) [AS64512i]
                   via 10.10.51.42 on eth0 [k8test3 11:36:22] (100) [AS64512i]
10.120.2.0/24      via 10.10.51.40 on eth0 [k8test2 11:36:21] * (100) [AS64512i]
10.120.0.0/24      via 10.10.51.39 on eth0 [k8test1 11:36:22] * (100) [AS64512i]
10.120.1.0/24      via 10.10.51.42 on eth0 [k8test3 11:36:22] * (100) [AS64512i]
```

Obvious difference is the /26 routes which looks to be something different about how ip addresses are being assigned to nodes.

The lesson may be that you cannot mix external and full mesh, without making the external part of the mesh, though I have to admit one of the first questions I asked in slack was if it was valid peering between a full mesh and an external node.  So this may just need to be a documentation 

  I intend to test some route reflector setups next.

**Comment by thomseddon** [comment] 2019-07-30 11:43
I've hit the same issue with a similar setup (https://github.com/projectcalico/node/issues/279)

I have opened this PR with a possible solution: https://github.com/projectcalico/confd/pull/257

That PR actually represents a relatively large change in behavior so, as mentioned in the PR, I have also mocked up an alternative approach which more narrowly addresses this issue.

**Comment by neiljerram** [comment] 2019-08-01 14:43
Thanks everyone for reporting and analysing this.  When I last looked closely at next hop self and next hop keep, it was for a PR https://github.com/projectcalico/node/pull/55 to remove "next hop self" from our BIRD config, and the most detailed reasoning for that change is in the commit message here: https://github.com/projectcalico/node/pull/55/commits/c6177d34a396ad22719079ac135f087e58a7c0be.

In summary, the reasoning of that change is that we don't want the "next hop self" behaviour anywhere, except for situations - specifically, exporting local workload routes - where BIRD would do that behaviour by default anyway.  Hence, we shouldn't be explicitly configuring "next hop self" anywhere.

I think what we're seeing now is that BIRD is doing the "next hop self" behaviour for all /32 routes on its RR peerings.  It feels like it would be a very plausible fix to add "next hop keep" to RR configs, to override that, but I'd also like to understand which condition of this relevant BIRD code -
```
   if (p->cf->next_hop_self ||
      rta->dest != RTD_ROUTER ||
      ipa_equal(rta->gw, IPA_NONE) ||
      ipa_is_link_local(rta->gw) ||
      (!p->is_internal && !p->cf->next_hop_keep &&
       (!p->neigh || (rta->iface != p->neigh->iface))))
    set_next_hop(z, p->source_addr);
  else
    set_next_hop(z, rta->gw);
```
is causing us to get the next hop self behaviour for those routes.  Is that obvious to anyone?

**Comment by cfiske** [comment] 2019-10-17 05:10
Here's the logic being evaluated, as near as I can reconstruct from inspecting the `bird` codebase:
```
if - 'next hop self' is set
   OR - route destination is a neighboring router
   OR - next hop is 0.0.0.0 (or an invalid IP? not clear)
   OR - next hop is a link-local IP
   OR - peer is eBGP
        AND - 'next hop keep' is not set
        AND - peer is configured for eBGP multihop
              OR - next hop interface doesn't match BGP peer interface
```
I don't see any of those being true in the RR case:

- 'next hop self' is not set (its removal is potentially the basis for this issue)
- Destination is a serviceCIDR, not a neighboring router (node)
- Next hop is a valid, non-default IP (adjacent node)
- Next hop is not link-local
- Peer is iBGP in the RR case, not eBGP

Scratching my head on this one.

**Comment by neiljerram** [comment] 2020-01-06 18:55
With apologies for the long hiatus...

Thanks @cfiske for your analysis above.  It explains the original observation from @mleklund : in his case, the peering (from each Calico node to the external BIRD) is eBGP, because the external BIRD has a different AS number.

For @mleklund 's case I think the most sensible fix is to configure the external BIRD with the same AS number; then the peerings become iBGP, and anyway BIRD won't re-export routes from other nodes, because it will correctly assume that the external BIRD already has those routes directly from the relevant source nodes.  So, unless there is some reason why configuring the same AS number is problematic, I don't think we need to look at that case any further.

**Comment by neiljerram** [comment] 2020-01-06 19:24
@thomseddon Your report in https://github.com/projectcalico/node/issues/279 is eBGP also, and I've just commented more about that there.

**Comment by neiljerram** [comment] 2020-01-06 19:25
I feel confident now that this issue is a duplicate of https://github.com/projectcalico/node/issues/279, so I'll close this issue now, and let's continue the discussion at https://github.com/projectcalico/node/issues/279, to ensure that it's focussed on one place.

**Closed** 2020-01-06 19:26 UTC
Labels: kind/bug, priority/P2
